name: Deploy FastAPI Application with Nginx

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image for FastAPI
        run: |
          sudo docker build -t my-ai-app .
          sudo docker tag my-ai-app ${{ secrets.DOCKER_USERNAME }}/my-ai-app:latest
          sudo docker push ${{ secrets.DOCKER_USERNAME }}/my-ai-app:latest

      - name: SSH and deploy to EC2
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts
            sudo ssh -i ${{ secrets.EC2_SSH_KEY }} ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'ENDSSH'
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/my-ai-app:latest
            sudo docker-compose -f /home/ubuntu/docker-compose.yml up -d
            ENDSSH
