name: Deploy FastAPI Application with Nginx

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/fastapi_app .
          docker tag ${{ secrets.DOCKER_USERNAME }}/fastapi_app ${{ secrets.DOCKER_USERNAME }}/fastapi_app:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/fastapi_app:latest

      - name: SSH and deploy to EC2
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/fastapi_app:latest
            sudo docker stop fastapi_app || true
            sudo docker rm fastapi_app || true
            sudo docker run -d --name fastapi_app -p 80:8000 ${{ secrets.DOCKER_USERNAME }}/fastapi_app:latest
